services:
    frankenphp:
        restart: always
        build:
            dockerfile: frankenphp.Dockerfile
            context: .
        ports:
            - "8000:8000"
            - "8880:8880"
            - "5173:5173"
        networks:
            - app_network
        env_file:
            - .env
        depends_on:
            - pgsql
    pgsql:
        container_name: pgsql
        image: postgres:17-alpine3.20
        ports:
            - "5432:5432"
        networks:
            - app_network
        volumes:
            - 'pgsql:/var/lib/pgsql'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
    app_network:
        driver: bridge
volumes:
    pgsql:
        driver: local
